
#-----------------------------------------------------------------------

APP       := HQExtend
TARGET    := test
#DFLAGS    := all/O2/g
DFLAGS    := g 
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 

CFLAGS    := 

INCLUDE   += 
LIB       += 

USER_H    +=
USER_OBJ  +=
#-----------------------------------------------------------------------
include /home/tafjce/HQExtend/ConditionServer/ConditionServer.mk
include /home/tafjce/HQSys/LIBS/hqutils/hqutils.mk
include /usr/local/taf/cpp/makefile/makefile.taf.new

#-----------------------------------------------------------------------
